### PR TITLE
Update ci.yml

### PR DESCRIPTION
**Pull request by dereuromark**
Cronjob shouldnt be added
It disabled the complete CI now
You will have to manually turn it on again

### CODE REVIEW

**Comment by ndm2** [comment]
Pepperidge Farm remembers when Github would sent out E-Mails to notify about (soon to be) disabled workflows 😞

Anyways, schedule has been enabled again. Not sure why you'd want to remove it?

**Comment by dereuromark** [comment]
Because it would disable again after those days.
So in general not helpful IMO.
Better to let the actual PRs and commits spawn it.

**Comment by ndm2** [comment]
Well, I like to get notifications of possible problems ahead of time, that's pretty much the only reason for me to have this. Github's stupid auto-timeout is annoying, but I'd rather look into a way to keep it alive automatically than just ditching it. I'm also fine with re-enabling it manually when required, that just needs Github to reliably send notifications.

**Comment by dereuromark** [comment]
I hear you
There is a better way
Working on a cron based trigger via tooling to do this nightly
Maybe we can set up

**Comment by ndm2** [comment]
I don't like that the token for that API call must have repo write permissions, that's just ridiculous. Even the new fine-grained beta tokens don't allow to permit by endpoint, it's always read/write on a whole endpoints category. I mean, I just want to trigger a workflow, no need to allow the token to be used for approving PR workflows 😣

Anyways, I'll look into it.

**Comment by dereuromark** [comment]
Given the "average" activity on the repo I still recommend not using the crons which disable the CI for the next person to use it.

**Comment by ndm2** [comment]
I'll disable it once I've set up external triggers.

**Pull request closed without merging**
